Server:
  RunMode: debug
  HTTPPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/log
  logFileName: app
  logFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: hshgame
  Host: 127.0.0.1:3306
  DBName: blog_server
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30